### PR TITLE
Implement a new design for the rocket-league website

### PR DESCRIPTION
**Pull request by abitsalihu**
I implemented a new design for the rocket-league website.

Below is a video of how the new website design will look.

`Video:`

https://user-images.githubusercontent.com/94648837/210563930-0f1eb7ec-0e24-449d-84f7-c0e927f9e126.mov

### CODE REVIEW

**Comment by Maizuou** [comment]
Thanks a lot for the redesign <3. Looks very clean and I like the casual look. I test it out on a second branch and if everything works, I merge it to the main branch.  Need to improve my skills to get to this level 😅

**Comment by abitsalihu** [comment]
@Maizuou Happy to help. I tried to implement an API to showcase your stats from steam, but I couldn't do it with my API key. Maybe that can be a challenge for you in the future to implement it. I would love it if we connected on LinkedIn -- https://www.linkedin.com/in/abit-s/

**Comment by Maizuou** [comment]
I unfortunately don't have a LinkedIn account. The small car you show in the preview isn't there when I submitted it on the second branch. Could a path be wrongly set to cause this issue?
Bild_2023-01-04_152904088

**Comment by abitsalihu** [comment]
Hey @Maizuou, I had a problem with the `src` path, maybe recheck it and change it to the correct path since it already has the CSS and everything.

**Comment by Maizuou** [comment]
Ok thanks a lot again

**Pull request merged**
